### ISSUE TITLE
Docker requirements

### ISSUE THREAD

**Issue by mleotta** [Kitware/resonantgeo#2]
Can you provide some guidance in the readme about the requirements for versions of docker or other dependencies?  I tried to spin this up on Ubuntu 16.04 (actually Ubuntu 16.04 in Windows 10 WSL) but got errors related to the version of docker-compose I installed with apt-get install.  Are there recommendations for how I should obtain a compliant docker on a stock Ubuntu 16.04 machine?

**Comment by aashish24** [comment]
@opadron @matthewma7 fyi - an email was sent as well.

**Comment by matthewma7** [comment]
I am no expert myself. But I remember [this specific document](https://docs.docker.com/install/linux/docker-ce/ubuntu/) helped me upgrading docker on a Desktop Ubuntu 16.04

**Comment by opadron** [comment]
Hi, @mleotta. The link that @matthewma7 posted has all the instructions you'd need to install an up-to-date version of docker.  The version of docker-compose that you would get from pip should be the latest and should work, so no worries, there.

Let us know if you continue to run into issues.

**Comment by mleotta** [comment]
I have not had time to try this yet.  However, I would say that the issue should not be resolved until the readme has been updated to provide information about what the minimum requirements are for resonant geo (e.g. which version of docker, docker-compose, etc. are required).

**Comment by aashish24** [comment]
+1, @opadron could you please update README (or somewhere appropriate) information on minimum requirements so that users ensure that their system is good for rgeo?
