### ISSUE TITLE
Cleanup GeoJS event handler on destroy

### ISSUE THREAD

**Issue by matthewma7** [Kitware/resonantgeo#46]
I am not entirely sure about this, but it seems that we need to stop [this listener](https://github.com/Kitware/resonantgeo/blob/627fe15acac543bafdb43d5e9b2a46f932e16c97/src/components/geojs/GeojsWidgetLayer.vue) on destroy because in the application GeoJSWidgetLayer could have a shorter lifespan than the GeoJSViewport instance.

**Comment by matthewma7** [comment]
@aashish24 at this moment, when the GeojsWidgetLayer is destroyed, the method reposition() will continuously be called.

**Comment by aashish24** [comment]
> @aashish24 at this moment, when the GeojsWidgetLayer is destroyed, the method reposition() will continuously be called.

thanks for clarification.
