### ISSUE TITLE
Feature Request: Expose map zoom range as property of viewport

### ISSUE THREAD

**Issue by wphicks** [Kitware/resonantgeo#48]
It would be helpful to be able to set the zoom range of the geojs map in the geojs map viewport component from a parent component. As a specific example of why this would be useful, I currently have the following code in a parent component containing a geojs map viewport:

```javascript
this.map = this.$refs.mapViewport.$geojsMap // Probably shouldn't touch child's map directly
let zoomRange = this.map.zoomRange()
this.map.zoomRange({min: zoomRange.min, max: zoomRange.max + 4})
```

**Comment by jbeezley** [comment]
Sure, that's an easy change.
